'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '../../lib/supabase-browser';
const checks=['Kondisi visual diperiksa','Fungsi utama diuji','Panel/koneksi aman','Cleaning/housekeeping selesai','Parameter operasi dicatat'];
export default function PPMExecution(){const[rows,setRows]=useState([]),[msg,setMsg]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[edit,setEdit]=useState(null),[check,setCheck]=useState({}),[finding,setFinding]=useState(''),[action,setAction]=useState(''),[employees,setEmployees]=useState([]),[schedules,setSchedules]=useState({});
async function load(){setLoading(true);const [x,e,q]=await Promise.all([supabase.from('ppm_execution_steps').select('id,ppm_schedule_id,employee_id,started_at,completed_at,checklist,findings,corrective_action,qc_status,created_at').order('created_at',{ascending:false}).limit(300),supabase.from('employees').select('id,full_name,employee_no').eq('active',true),supabase.from('ppm_schedule').select('id,equipment_id,scheduled_date')]);const er=[x,e,q].find(v=>v.error);if(er)setMsg(er.error.message);else{setRows(x.data||[]);setEmployees(e.data||[]);const ids=(q.data||[]).map(v=>v.equipment_id).filter(Boolean);const a=ids.length?await supabase.from('equipment').select('id,asset_code,equipment_type,building_code').in('id',ids):{data:[]};const em=Object.fromEntries((a.data||[]).map(v=>[v.id,v]));setSchedules(Object.fromEntries((q.data||[]).map(v=>[v.id,{...v,equipment:em[v.equipment_id]}])))}setLoading(false)}useEffect(()=>{load()},[]);const emp=useMemo(()=>Object.fromEntries(employees.map(v=>[v.id,v])),[employees]);
async function save(){if(!edit)return;const selected=checks.map((name,i)=>({item:name,status:check[i]?'OK':'NOT_CHECKED'}));if(!selected.some(v=>v.status==='OK'))return setMsg('Minimal satu checklist harus OK.');setBusy(true);let r=await supabase.rpc('update_ppm_execution_details',{p_execution_id:edit.id,p_checklist:selected,p_findings:finding.trim()||null,p_corrective_action:action.trim()||null});if(!r.error)r=await supabase.rpc('complete_ppm_execution',{p_execution_id:edit.id});setBusy(false);setMsg(r.error?r.error.message:'PPM selesai dan menunggu QC.');if(!r.error){setEdit(null);setCheck({});setFinding('');setAction('');load()}}
return <main className="modulePage"><header className="moduleHead"><div><b>BSS ENGINEERING</b><h1>PPM Execution</h1></div><Link href="/">← Dashboard</Link></header><div className="moduleBody"><nav className="moduleNav"><Link href="/ppm">PPM Master</Link><Link href="/ppm-schedule">Schedule</Link><Link href="/ppm-execution">Execution</Link><Link href="/ppm-qc">QC</Link></nav>{msg&&<div className={'notice '+(msg.includes('selesai')?'success':'error')}>{msg}</div>}
{edit&&<section className="panel form"><h2>Checklist PPM</h2><p className="muted">Execution: {edit.id}</p>{checks.map((x,i)=><label key={x} style={{display:'flex',gap:10,alignItems:'center',margin:'10px 0'}}><input type="checkbox" checked={!!check[i]} onChange={e=>setCheck(c=>({...c,[i]:e.target.checked}))}/>{x}</label>)}<textarea value={finding} onChange={e=>setFinding(e.target.value)} placeholder="Temuan / finding"/><textarea value={action} onChange={e=>setAction(e.target.value)} placeholder="Tindakan korektif"/><div className="actions"><button className="btn primary" disabled={busy} onClick={save}>{busy?'Menyimpan…':'Simpan & Complete'}</button><button className="btn secondary" onClick={()=>setEdit(null)}>Batal</button></div></section>}
<section className="panel tablePanel"><div className="panelTitle"><div><h2>Daftar Eksekusi</h2><small>{rows.length} execution</small></div><button className="btn secondary" onClick={load}>↻ Refresh</button></div>{loading?<div className="loading">Memuat…</div>:rows.length===0?<div className="empty">Belum ada eksekusi. Tetapkan teknisi di Schedule lalu mulai.</div>:<div className="tableWrap"><table><thead><tr><th>Mulai</th><th>Teknisi</th><th>Equipment</th><th>Status</th><th>QC</th><th>Finding</th><th>Aksi</th></tr></thead><tbody>{rows.map(r=>{const e=emp[r.employee_id],s=schedules[r.ppm_schedule_id];return <tr key={r.id}><td>{r.started_at?new Date(r.started_at).toLocaleString('id-ID'):'—'}</td><td>{e?.full_name||r.employee_id}</td><td>{s?.equipment?.asset_code||'—'}</td><td>{r.completed_at?'COMPLETED':'IN_PROGRESS'}</td><td>{r.qc_status||'PENDING'}</td><td>{r.findings||'—'}</td><td>{!r.completed_at&&<button className="mini" onClick={()=>{setEdit(r);const c=Array.isArray(r.checklist)?r.checklist:[];setCheck(Object.fromEntries(checks.map((x,i)=>[i,c[i]?.status==='OK'])));setFinding(r.findings||'');setAction(r.corrective_action||'')}}>Checklist</button>}</td></tr>})}</tbody></table></div>}</section></div></main>}
