'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {supabase} from '../../lib/supabase-browser';
const checks=['Kondisi visual diperiksa','Fungsi utama diuji','Panel/koneksi aman','Cleaning/housekeeping selesai','Parameter operasi dicatat'];
export default function PPMExecution(){const[rows,setRows]=useState([]),[msg,setMsg]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[edit,setEdit]=useState(null),[check,setCheck]=useState({}),[finding,setFinding]=useState(''),[action,setAction]=useState('');
 async function load(){setLoading(true);const{data,error}=await supabase.from('ppm_execution_steps').select('id,ppm_schedule_id,employee_id,started_at,completed_at,checklist,findings,corrective_action,qc_status,created_at').order('created_at',{ascending:false}).limit(200);if(error)setMsg(error.message);else setRows(data||[]);setLoading(false)}useEffect(()=>{load()},[]);
 async function save(){if(!edit)return;const selected=checks.filter((_,i)=>check[i]).map((name,i)=>({item:name,status:'OK'}));if(!selected.length)return setMsg('Minimal satu checklist harus dicentang.');setBusy(true);let r=await supabase.rpc('update_ppm_execution_details',{p_execution_id:edit.id,p_checklist:selected,p_findings:finding,p_corrective_action:action});if(!r.error)r=await supabase.rpc('complete_ppm_execution',{p_execution_id:edit.id});setBusy(false);setMsg(r.error?r.error.message:'PPM selesai dan menunggu QC.');if(!r.error){setEdit(null);setCheck({});setFinding('');setAction('');load()}}
 async function start(scheduleId){setBusy(true);const{error}=await supabase.rpc('start_ppm_execution',{p_schedule_id:scheduleId});setBusy(false);setMsg(error?error.message:'Eksekusi dimulai. Buka jadwal untuk detail.');if(!error)load()}
 return <main className="modulePage"><header className="moduleHead"><div><b>BSS ENGINEERING</b><h1>PPM Execution</h1></div><Link href="/">← Dashboard</Link></header><div className="moduleBody"><nav className="moduleNav"><Link href="/ppm">PPM Master</Link><Link href="/ppm-schedule">Schedule</Link><Link href="/ppm-execution">Execution</Link><Link href="/ppm-qc">QC</Link></nav>{msg&&<div className={'notice '+(msg.includes('selesai')||msg.includes('dimulai')?'success':'error')}>{msg}</div>}
 {edit&&<section className="panel form"><h2>Checklist PPM</h2><p className="muted">Execution ID: {edit.id}</p>{checks.map((x,i)=><label key={x} style={{display:'flex',gap:10,alignItems:'center',margin:'10px 0'}}><input type="checkbox" checked={!!check[i]} onChange={e=>setCheck(c=>({...c,[i]:e.target.checked}))}/>{x}</label>)}<textarea value={finding} onChange={e=>setFinding(e.target.value)} placeholder="Temuan / finding"/><textarea value={action} onChange={e=>setAction(e.target.value)} placeholder="Tindakan korektif / pekerjaan yang dilakukan"/><div className="actions"><button className="btn primary" disabled={busy} onClick={save}>Simpan & Complete</button><button className="btn secondary" onClick={()=>setEdit(null)}>Batal</button></div></section>}
 <section className="panel tablePanel"><div className="panelTitle"><div><h2>Daftar Eksekusi</h2><small>{rows.length} execution</small></div><button className="btn secondary" onClick={load}>↻ Refresh</button></div>{loading?<div className="loading">Memuat…</div>:rows.length===0?<div className="empty">Belum ada eksekusi. Tetapkan teknisi di PPM Schedule lalu klik Mulai.</div>:<div className="tableWrap"><table><thead><tr><th>Mulai</th><th>Employee</th><th>Status</th><th>QC</th><th>Finding</th><th>Aksi</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.started_at?new Date(r.started_at).toLocaleString('id-ID'):'—'}</td><td>{r.employee_id}</td><td>{r.completed_at?'COMPLETED':'IN_PROGRESS'}</td><td>{r.qc_status||'PENDING'}</td><td>{r.findings||'—'}</td><td>{!r.completed_at&&<button className="mini" onClick={()=>{setEdit(r);setFinding(r.findings||'');setAction(r.corrective_action||'')}}>Checklist</button>}</td></tr>)}</tbody></table></div>}</section></div></main>}
