'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {supabase} from '../../lib/supabase-browser';

const freq={DAILY:'Harian',WEEKLY:'Mingguan',MONTHLY:'Bulanan','3_MONTHLY':'3 Bulanan','6_MONTHLY':'6 Bulanan',YEARLY:'Tahunan'};
const statuses=['PLANNED','ASSIGNED','IN_PROGRESS','OVERDUE','DONE','CANCELLED'];
export default function PPMSchedule(){
 const [rows,setRows]=useState([]),[employees,setEmployees]=useState([]),[buildings,setBuildings]=useState([]),[building,setBuilding]=useState('ALL'),[status,setStatus]=useState('ALL'),[selected,setSelected]=useState(null),[assignee,setAssignee]=useState(''),[msg,setMsg]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 async function load(){setLoading(true);setMsg('');try{const [s,e,b]=await Promise.all([supabase.from('ppm_schedule').select('id,equipment_id,scheduled_date,frequency,assigned_to,status,result,checklist_score,notes,ppm_master_task_id,created_at').order('scheduled_date').limit(500),supabase.from('employees').select('id,employee_no,full_name,building_code,work_type,active').eq('active',true).order('full_name'),supabase.from('buildings').select('code,name').eq('active',true).order('display_order')]);const er=[s,e,b].find(x=>x.error);if(er)throw er.error;const eq=await supabase.from('equipment').select('id,asset_code,building_code,equipment_type');if(eq.error)throw eq.error;const em=Object.fromEntries((eq.data||[]).map(x=>[x.id,x]));setRows((s.data||[]).map(x=>({...x,equipment:em[x.equipment_id]})));setEmployees(e.data||[]);setBuildings(b.data||[])}catch(e){setMsg(e.message||'Gagal memuat jadwal')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const filtered=rows.filter(r=>(building==='ALL'||r.equipment?.building_code===building)&&(status==='ALL'||r.status===status));
 async function assign(){if(!selected||!assignee)return;setBusy(true);const{error}=await supabase.rpc('assign_ppm_schedule',{p_schedule_id:selected.id,p_employee_id:assignee});setBusy(false);setMsg(error?error.message:'PPM berhasil ditugaskan.');if(!error){setSelected(null);setAssignee('');load()}}
 async function unassign(id){setBusy(true);const{error}=await supabase.rpc('unassign_ppm_schedule',{p_schedule_id:id});setBusy(false);setMsg(error?error.message:'Penugasan dibatalkan.');if(!error)load()}
 async function start(id){setBusy(true);const{data,error}=await supabase.rpc('start_ppm_execution',{p_schedule_id:id});setBusy(false);setMsg(error?error.message:`Eksekusi dimulai: ${data}`);if(!error){window.location.href='/ppm-execution';}}
 return <main className="modulePage"><header className="moduleHead"><div><b>BSS ENGINEERING</b><h1>PPM Schedule Control</h1></div><div><span className="statusDot">● Live Database</span> <Link href="/">← Dashboard</Link></div></header><div className="moduleBody"><nav className="moduleNav"><Link href="/ppm">PPM Master</Link><Link href="/ppm-schedule">Schedule</Link><Link href="/ppm-execution">Execution</Link><Link href="/ppm-qc">QC</Link><Link href="/ppm-import">Import</Link></nav>{msg&&<div className={'notice '+(msg.includes('berhasil')||msg.includes('dimulai')?'success':'error')}>{msg}</div>}
 <section className="panel form"><div className="formGrid"><label>Gedung<select value={building} onChange={e=>setBuilding(e.target.value)}><option value="ALL">Semua Gedung</option>{buildings.map(b=><option key={b.code} value={b.code}>{b.name}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">Semua Status</option>{statuses.map(x=><option key={x}>{x}</option>)}</select></label></div><p className="muted">Manager dapat menetapkan teknisi sebelum eksekusi. Tidak ada penugasan otomatis sehingga data operasional tetap valid.</p></section>
 {selected&&<section className="panel form"><h2>Assign PPM</h2><p>{selected.equipment?.asset_code||'Equipment'} • {selected.scheduled_date} • {freq[selected.frequency]||selected.frequency}</p><div className="formGrid"><select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Pilih teknisi</option>{employees.filter(e=>!e.building_code||e.building_code===selected.equipment?.building_code).map(e=><option key={e.id} value={e.id}>{e.full_name}{e.employee_no?' • '+e.employee_no:''}</option>)}</select><button className="btn primary" disabled={busy||!assignee} onClick={assign}>Simpan Penugasan</button><button className="btn secondary" onClick={()=>setSelected(null)}>Batal</button></div></section>}
 <section className="panel tablePanel"><div className="panelTitle"><div><h2>Jadwal PPM</h2><small>{filtered.length} jadwal ditampilkan</small></div><button className="btn secondary" onClick={load}>↻ Refresh</button></div>{loading?<div className="loading">Memuat…</div>:<div className="tableWrap"><table><thead><tr><th>Tanggal</th><th>Gedung</th><th>Equipment</th><th>Frekuensi</th><th>Teknisi</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{filtered.map(r=>{const emp=employees.find(e=>e.id===r.assigned_to);return <tr key={r.id}><td>{r.scheduled_date}</td><td>{r.equipment?.building_code||'—'}</td><td><b>{r.equipment?.asset_code||'—'}</b><br/><small>{r.equipment?.equipment_type||''}</small></td><td>{freq[r.frequency]||r.frequency}</td><td>{emp?.full_name||'Belum ditugaskan'}</td><td>{r.status}</td><td><button className="mini" onClick={()=>{setSelected(r);setAssignee(r.assigned_to||'')}}>Assign</button>{r.assigned_to&&['ASSIGNED','PLANNED','OVERDUE'].includes(r.status)&&<button className="mini" disabled={busy} onClick={()=>start(r.id)}>Mulai</button>}{r.assigned_to&&<button className="mini danger" disabled={busy} onClick={()=>unassign(r.id)}>Unassign</button>}</td></tr>})}</tbody></table></div>}</section></div></main>}
