'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {supabase} from '../../lib/supabase-browser';
const TYPES={attendance:'attendance',complaints:'complaints','work-orders':'work_orders',ppm:'ppm_schedule',equipment:'equipment',kpi:'kpi_monthly'};
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
const display=v=>typeof v==='object'&&v!==null?JSON.stringify(v):String(v??'—');
export default function Reports(){
 const[type,setType]=useState('complaints'),[from,setFrom]=useState(new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10)),[to,setTo]=useState(new Date().toISOString().slice(0,10)),[rows,setRows]=useState([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);setMsg('');const table=TYPES[type];let q=supabase.from(table).select('*');if(type==='attendance'||type==='complaints'||type==='work-orders')q=q.gte(type==='attendance'?'work_date':type==='complaints'?'reported_at':'opened_at',from).lte(type==='attendance'?'work_date':type==='complaints'?'reported_at':'opened_at',type==='attendance'?to:to+'T23:59:59');else if(type==='ppm')q=q.gte('scheduled_date',from).lte('scheduled_date',to);else if(type==='kpi')q=q.gte('period_month',from).lte('period_month',to);const{data,error}=await q.limit(5000);setBusy(false);if(error)setMsg(error.message);else setRows(data||[])}
 useEffect(()=>{load()},[type]);
 function exportExcel(){if(!rows.length)return setMsg('Tidak ada data untuk diekspor.');const cols=Object.keys(rows[0]).slice(0,12);const body=rows.map(r=>`<Row>${cols.map(k=>`<Cell><Data ss:Type="String">${esc(display(r[k]))}</Data></Cell>`).join('')}</Row>`).join('');const header=`<Row>${cols.map(k=>`<Cell><Data ss:Type="String">${esc(k)}</Data></Cell>`).join('')}</Row>`;const xml=`<?xml version="1.0" encoding="UTF-8"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Report"><Table>${header}${body}</Table></Worksheet></Workbook>`;const blob=new Blob([xml],{type:'application/vnd.ms-excel;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`BSS_${type}_${from}_${to}.xls`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);setMsg('Excel berhasil dibuat.');}
 return <main className="modulePage"><header className="moduleHead"><div><b>BSS ENGINEERING</b><h1>Report & Export Center</h1></div><Link href="/">← Dashboard</Link></header><div className="moduleBody"><nav className="moduleNav"><Link href="/reports">Laporan</Link><Link href="/kpi">KPI</Link><Link href="/management">Management</Link></nav>{msg&&<div className="notice success">{msg}</div>}<section className="panel form"><div className="formGrid"><label>Jenis laporan<select value={type} onChange={e=>setType(e.target.value)}><option value="attendance">Absensi</option><option value="complaints">Complaint</option><option value="work-orders">Work Order</option><option value="ppm">PPM Schedule</option><option value="equipment">Equipment</option><option value="kpi">KPI</option></select></label><label>Dari<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Sampai<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><div className="actions"><button className="btn primary" disabled={busy} onClick={load}>Tampilkan</button><button className="btn secondary" disabled={!rows.length} onClick={exportExcel}>Export Excel</button><button className="btn secondary" disabled={!rows.length} onClick={()=>window.print()}>Print / PDF</button></div></section><section className="panel tablePanel"><div className="panelTitle"><div><h2>Preview</h2><small>{rows.length} record • maksimum 5.000</small></div></div>{rows.length?<div className="tableWrap"><table><thead><tr>{Object.keys(rows[0]).slice(0,12).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{rows.slice(0,200).map((r,i)=><tr key={r.id||i}>{Object.keys(rows[0]).slice(0,12).map(k=><td key={k}>{display(r[k])}</td>)}</tr>)}</tbody></table></div>:<div className="empty">Belum ada data pada periode ini.</div>}</section></div></main>
}
