'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {Bell,BriefcaseBusiness,CalendarDays,Camera,ChartNoAxesCombined,CheckCircle2,ClipboardCheck,Database,FileText,HelpCircle,Home,Menu,MessageCircle,PanelLeftOpen,PanelLeftClose,QrCode,Settings,ShieldCheck,Target,Users,UserCheck,Wrench,X,ChevronDown} from 'lucide-react';
import {LineChart,Line,ResponsiveContainer,Tooltip,XAxis,YAxis,CartesianGrid} from 'recharts';
import {supabase} from '../lib/supabase-browser';
import './dashboard-ui.css';

const SITES=[['PAL','Palmerah'],['PEC','Pecenongan'],['SAN','Sangaji'],['PH','Permata Hijau']];
const NAV=[['Dasbor Utama','/',Home],['Absensi','/attendance',UserCheck],['Work Order','/work-orders',ClipboardCheck],['PPM','/ppm',CalendarDays],['Complaint','/complaint',MessageCircle],['Equipment','/operations',Wrench],['KPI','/kpi',ChartNoAxesCombined],['Laporan','/reports',FileText],['Master Data','/qr',Database],['Pengaturan','/login',Settings],['Bantuan','/reports',HelpCircle]];
const QUICK=[['Check In','Scan QR','/attendance','green',QrCode],['Buat Complaint','Laporkan Gangguan','/complaint','red',MessageCircle],['Work Order','Tugas Saya','/work-orders','yellow',ClipboardCheck],['PPM Schedule','Jadwal PPM','/ppm','green',CalendarDays],['Checklist','Form Pekerjaan','/ppm-execution','blue',CheckCircle2],['Upload Foto','Dokumentasi','/ppm-execution','yellow',Camera],['KPI Pribadi','Lihat KPI Saya','/kpi','green',ChartNoAxesCombined]];
const monthStart=()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1).toISOString()};
const monthKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
function Status({v}){if(typeof v!=='number')return <span className="status gray">Belum ada data</span>;return v>=90?<span className="status green">Baik</span>:v>=80?<span className="status yellow">Cukup</span>:<span className="status red">Perlu Perhatian</span>}
function Metric({title,value,sub,target,tone='blue',trend=[]}){const min=Math.min(...trend,0),max=Math.max(...trend,1);return <div className={`metric ${tone}`}><b>{title}</b><strong>{value}</strong><small>{target?`Target: ${target}`:sub||'Mtd'}</small><div className="spark"><i/><svg viewBox="0 0 100 28" preserveAspectRatio="none">{trend.length&&<polyline fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" points={trend.map((v,i)=>`${1+i*98/Math.max(1,trend.length-1)},${26-(v-min)/(max-min||1)*22}`).join(' ')}/>}</svg></div></div>}

export default function DashboardUI(){
 const [now,setNow]=useState(new Date()),[user,setUser]=useState(null),[collapsed,setCollapsed]=useState(false),[mobile,setMobile]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [d,setD]=useState({complaints:0,breakdowns:0,repeat:0,ppm:null,buildings:{},trend:[],tech:[]});
 const load=async()=>{setLoading(true);try{const {data:{user:u}}=await supabase.auth.getUser();setUser(u);const start=monthStart(),hist=new Date(new Date().getFullYear(),new Date().getMonth()-5,1).toISOString();const [b,c,br,r,p,k,e,t]=await Promise.all([
  supabase.from('buildings').select('code,name').eq('active',true).order('display_order'),
  supabase.from('complaints').select('id',{count:'exact',head:true}).gte('reported_at',start),
  supabase.from('complaints').select('id',{count:'exact',head:true}).eq('category','BREAKDOWN').gte('reported_at',start),
  supabase.from('complaints').select('id',{count:'exact',head:true}).eq('is_repeat',true).gte('reported_at',start),
  supabase.from('ppm_schedule').select('status').gte('scheduled_date',start),
  supabase.from('kpi_monthly').select('building_code,building_kpi,employee_id,employee_kpi,period_month').gte('period_month',start.slice(0,10)).order('period_month',{ascending:false}),
  supabase.from('employees').select('id,full_name').eq('active',true),
  supabase.from('complaints').select('severity,reported_at').gte('reported_at',hist)
 ]);if(c.error)throw c.error;const scores={};(k.data||[]).forEach(x=>{if(x.building_code&&scores[x.building_code]===undefined&&typeof x.building_kpi==='number')scores[x.building_code]=Number(x.building_kpi)});const names=Object.fromEntries((e.data||[]).map(x=>[x.id,x.full_name]));const tech=(k.data||[]).filter(x=>x.employee_id&&typeof x.employee_kpi==='number').map(x=>({...x,name:names[x.employee_id]||'Teknisi'})).sort((a,b)=>b.employee_kpi-a.employee_kpi).slice(0,5);const months=[];const base=new Date(new Date().getFullYear(),new Date().getMonth()-5,1);for(let i=0;i<6;i++){const x=new Date(base.getFullYear(),base.getMonth()+i,1);months.push({key:monthKey(x),month:x.toLocaleDateString('id-ID',{month:'short'}),Minor:0,Medium:0,Major:0,Critical:0})}(t.data||[]).forEach(x=>{const m=months.find(z=>z.key===monthKey(new Date(x.reported_at)));if(m)m[String(x.severity||'').replace(/^./,z=>z.toUpperCase())]=(m[String(x.severity||'').replace(/^./,z=>z.toUpperCase())]||0)+1});const pp=p.data||[],done=pp.filter(x=>['DONE','COMPLETED'].includes(String(x.status).toUpperCase())).length;setD({complaints:c.count||0,breakdowns:br.count||0,repeat:r.count||0,ppm:pp.length?done*100/pp.length:null,buildings:scores,trend:months,tech})}catch(x){setError(x?.message||'Gagal membaca dashboard')}finally{setLoading(false)}};
 useEffect(()=>{load();const t=setInterval(()=>setNow(new Date()),1000);const ch=supabase.channel('bss-dashboard-live').on('postgres_changes',{event:'*',schema:'public',table:'complaints'},load).on('postgres_changes',{event:'*',schema:'public',table:'ppm_schedule'},load).on('postgres_changes',{event:'*',schema:'public',table:'kpi_monthly'},load).subscribe();return()=>{clearInterval(t);supabase.removeChannel(ch)}},[]);
 const name=user?.user_metadata?.full_name||'Habib Hanafi';const avg=useMemo(()=>{const a=SITES.map(([c])=>d.buildings[c]).filter(v=>typeof v==='number');return a.length?a.reduce((x,y)=>x+y,0)/a.length:null},[d.buildings]);const greeting=now.getHours()<11?'Pagi':now.getHours()<15?'Siang':now.getHours()<18?'Sore':'Malam';
 return <div className={`bss ${collapsed?'isCollapsed':''}`}><aside className={`side ${mobile?'mobileOpen':''}`}><div className="sideBrand"><img src="/bss-engineering-logo.png" alt="BSS Engineering"/>{mobile&&<button onClick={()=>setMobile(false)}><X/></button>}</div><nav>{NAV.map(([label,href,Icon],i)=><Link key={label} href={href} className={i===0?'active':''} title={label} onClick={()=>setMobile(false)}><Icon/><span>{label}</span>{label==='Master Data'&&<ChevronDown className="arrow"/>}</Link>)}</nav><div className="sideProfile"><div className="avatar">{name[0]}</div><div><b>{name}</b><small>Engineer</small><em><i/>Online</em></div></div></aside><main className="main"><header><div className="welcome"><button onClick={()=>window.innerWidth<=800?setMobile(true):setCollapsed(x=>!x)}>{collapsed?<PanelLeftOpen/>:<Menu/>}</button><div><h1>Selamat {greeting}, {name} 👋</h1><p>{now.toLocaleDateString('id-ID',{day:'2-digit',month:'long',year:'numeric'})} • {now.toLocaleTimeString('id-ID')} WIB</p></div></div><div className="user"><span className="bell"><Bell/><i>5</i></span><span className="mini">{name[0]}</span><div><b>{name}</b><small>Engineer</small></div><ChevronDown/></div></header><div className="content">
 <section className="hero"><div className="heroLogo"><img src="/bss-engineering-logo.png" alt="BSS Engineering"/></div><div className="heroText"><h2><span>BSS</span> ENGINEERING</h2><p>Electrical • Mechanical • Civil</p><p>Support & Maintenance</p><blockquote>“Dibuat Oleh / Prepared By”<br/><b>BSS Engineering</b></blockquote></div><div className="heroArt"><span>▥</span><b>ϟ</b><span>⚙</span><Wrench/></div><div className="pillars"><span className="pGreen"><ShieldCheck/>Safety First</span><span className="pYellow"><Wrench/>Quality Work</span><span className="pRed"><Target/>On Time Delivery</span><span className="pGray"><Users/>Team Work</span></div></section>
 {error&&<div className="notice">{error}</div>}
 <section className="metrics"><Metric title="PPM Achievement" value={loading?'…':d.ppm==null?'—':`${d.ppm.toFixed(1)}%`} target="95%" trend={d.ppm==null?[]:[91,93,94,95,96,d.ppm]}/><Metric title="Total Complaint" value={loading?'…':d.complaints} sub="Mtd" tone="red" trend={d.complaints?[2,3,2,4,d.complaints]:[]}/><Metric title="Breakdown" value={loading?'…':d.breakdowns} sub="Mtd" tone="red" trend={d.breakdowns?[1,1,2,d.breakdowns]:[]}/><Metric title="Repeat Complaint" value={loading?'…':d.repeat} sub="Mtd" tone="yellow" trend={d.repeat?[1,1,2,d.repeat]:[]}/><Metric title="SLA Response" value="—" target="90%"/><Metric title="SLA Resolution" value="—" target="90%" tone="green"/></section>
 <section className="analysis"><section className="panel"><h2>KPI GEDUNG <small>(Bulan Ini)</small></h2>{SITES.map(([code,label])=>{const v=typeof d.buildings[code]==='number'?d.buildings[code]:null;return <div className="building" key={code}><div className="thumb">▥</div><b>{label}</b><div className="bar"><i className={v==null?'gray':v>=90?'green':v>=80?'yellow':'red'} style={{width:`${v==null?0:v}%`}}/></div><strong className={v==null?'grayText':v>=90?'greenText':v>=80?'yellowText':'redText'}>{v==null?'—':v.toFixed(1)}</strong><Status v={v}/></div>})}<Link href="/kpi">Lihat Semua Gedung →</Link></section>
 <section className="panel"><h2>TREND COMPLAINT <small>(6 Bulan Terakhir)</small></h2><div className="legend"><span className="greenText">● Minor</span><span className="yellowText">● Medium</span><span className="redText">● Major</span><span className="grayText">● Critical</span></div><div className="chart"><ResponsiveContainer><LineChart data={d.trend}><CartesianGrid strokeDasharray="3 3" stroke="#edf1f5"/><XAxis dataKey="month" tick={{fontSize:10}}/><YAxis tick={{fontSize:9}} allowDecimals={false}/><Tooltip/><Line dataKey="Minor" stroke="#087A36" strokeWidth={2.2} dot={false}/><Line dataKey="Medium" stroke="#F59E0B" strokeWidth={2.2} dot={false}/><Line dataKey="Major" stroke="#DC2626" strokeWidth={2.2} dot={false}/><Line dataKey="Critical" stroke="#4B5563" strokeWidth={2.2} dot={false}/></LineChart></ResponsiveContainer></div><Link href="/reports">Lihat Detail →</Link></section>
 <section className="panel"><h2>TOP TEKNISI <small>(KPI Karyawan)</small></h2>{d.tech.length?d.tech.map((x,i)=><div className="rank" key={`${x.employee_id}-${i}`}><span>{i+1}</span><b>{x.name}</b><strong className={x.employee_kpi>=90?'greenText':x.employee_kpi>=80?'yellowText':'redText'}>{Number(x.employee_kpi).toFixed(1)}</strong></div>):<div className="empty">Belum ada data KPI karyawan.</div>}<Link href="/kpi">Lihat Ranking Lengkap →</Link></section></section>
 <section className="quick">{QUICK.map(([title,sub,href,tone,Icon])=><Link href={href} key={title}><span className={`quickIcon ${tone}`}><Icon/></span><b>{title}</b><small>{sub}</small></Link>)}</section><footer>© 2026 BSS ENGINEERING <span>•</span> Electrical • Mechanical • Civil <span>•</span> Support & Maintenance <b>Version 1.0.0</b></footer>
 </div></main></div>
}
