'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {QRCodeSVG} from 'qrcode.react';
import {supabase} from '../../lib/supabase-browser';
export default function QR(){const[sites,setSites]=useState([]),[qrs,setQrs]=useState([]),[building,setBuilding]=useState(''),[label,setLabel]=useState('QR Utama'),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[camera,setCamera]=useState(false);const video=useRef(null),stream=useRef(null);
 async function load(){const{data:b}=await supabase.from('buildings').select('code,name,latitude,longitude,geofence_radius_m').eq('active',true).order('name');setSites(b||[]);if(!building&&b?.length)setBuilding(b[0].code);const{data:q}=await supabase.from('qr_locations').select('id,building_code,label,active,rotation_seconds').order('building_code');setQrs(q||[])}useEffect(()=>{load();return()=>stream.current?.getTracks().forEach(t=>t.stop())},[]);
 async function create(){setBusy(true);const{error}=await supabase.from('qr_locations').insert({building_code:building,label,secret_hash:crypto.randomUUID().replaceAll('-',''),rotation_seconds:60,active:true});setBusy(false);setMsg(error?error.message:'QR berhasil dibuat dan tersimpan di Supabase.');if(!error)load()}
 function gps(){navigator.geolocation?.getCurrentPosition(async p=>{setBusy(true);const{error}=await supabase.from('buildings').update({latitude:p.coords.latitude,longitude:p.coords.longitude}).eq('code',building);setBusy(false);setMsg(error?error.message:`Lokasi ${building} disimpan: ${p.coords.latitude.toFixed(6)}, ${p.coords.longitude.toFixed(6)} ±${Math.round(p.coords.accuracy)}m`);load()},e=>setMsg('GPS: '+e.message),{enableHighAccuracy:true,timeout:20000,maximumAge:0})}
 async function scan(){if(!('BarcodeDetector'in window))return setMsg('Browser ini belum mendukung BarcodeDetector. Masukkan UUID QR secara manual di Absensi.');setCamera(true);stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});video.current.srcObject=stream.current;await video.current.play();const detector=new BarcodeDetector({formats:['qr_code']});const loop=async()=>{if(!video.current||!camera)return;try{const found=await detector.detect(video.current);if(found[0]?.rawValue){navigator.clipboard?.writeText(found[0].rawValue);setMsg('QR terbaca: '+found[0].rawValue);stop()}}catch{}requestAnimationFrame(loop)};loop()}
 function stop(){setCamera(false);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null}
 return <main className="qrPage"><header className="moduleHead"><div><b>BSS ENGINEERING</b><h1>QR & Master Lokasi</h1></div><Link href="/">← Dashboard</Link></header><div className="qrBody">{msg&&<div className="notice success">{msg}</div>}<section className="panel"><h2>1. Atur koordinat 4 gedung</h2><p className="muted">Lakukan sekali dari lokasi gedung. Koordinat dipakai untuk geofence absensi.</p><div className="formGrid"><select value={building} onChange={e=>setBuilding(e.target.value)}>{sites.map(s=><option key={s.code} value={s.code}>{s.name}</option>)}</select><button className="btn primary" disabled={busy} onClick={gps}>📍 Simpan GPS Gedung</button></div><div className="siteGrid">{sites.map(s=><div className="siteCard" key={s.code}><b>{s.name}</b><span>{s.latitude?`${Number(s.latitude).toFixed(6)}, ${Number(s.longitude).toFixed(6)}`:'Koordinat belum diisi'}</span><small>Radius {s.geofence_radius_m||75} m</small></div>)}</div></section><section className="panel"><h2>2. Buat / cetak QR lokasi</h2><div className="formGrid"><input value={label} onChange={e=>setLabel(e.target.value)} placeholder="Label QR"/><button className="btn primary" disabled={busy||!building} onClick={create}>+ Buat QR</button><button className="btn secondary" onClick={()=>window.print()}>🖨 Cetak</button><button className="btn secondary" onClick={scan}>📷 Test Scan</button></div></section>{camera&&<section className="panel scanner"><video ref={video} playsInline muted/><button className="btn danger" onClick={stop}>Tutup Scanner</button></section>}<section className="qrGrid">{qrs.map(q=><div className="qrCard" key={q.id}><QRCodeSVG value={q.id} size={180}/><b>{q.label}</b><small>{q.building_code} • rotasi {q.rotation_seconds}s</small><code>{q.id}</code></div>)}</section></div></main>}
