'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {useParams} from 'next/navigation';
import {supabase,supabaseConfigured} from '../../lib/supabase-browser';
const labels={attendance:'Absensi',complaint:'Complaint','work-orders':'Work Order',ppm:'PPM',kpi:'KPI',operations:'Equipment',reports:'Laporan',management:'Management','ppm-qc':'PPM QC','ppm-schedule':'PPM Schedule','ppm-import':'PPM Import','ppm-execution':'PPM Execution','attendance-monitor':'Monitor Absensi',login:'Login'};
const tableMap={attendance:'attendance',complaint:'complaints','work-orders':'work_orders',ppm:'ppm_schedule',kpi:'kpi_monthly',operations:'equipment','ppm-schedule':'ppm_schedule','ppm-qc':'ppm_executions'};
const nav=[['/','Dashboard'],['/attendance','Absensi'],['/complaint','Complaint'],['/work-orders','WO'],['/ppm','PPM'],['/operations','Equipment'],['/kpi','KPI'],['/reports','Laporan']];
export default function Module(){const {module:key}=useParams();const title=labels[key]||key;const[rows,setRows]=useState([]),[msg,setMsg]=useState(''),[loading,setLoading]=useState(true),[qr,setQr]=useState(''),[lat,setLat]=useState(''),[lng,setLng]=useState(''),[accuracy,setAccuracy]=useState(''),[description,setDescription]=useState(''),[severity,setSeverity]=useState('MEDIUM'),[status,setStatus]=useState('OPEN'),[busy,setBusy]=useState(false);const table=tableMap[key];const fields=useMemo(()=>rows.length?Object.keys(rows[0]).slice(0,12):[],[rows]);
 async function load(){if(!supabase){setMsg('Supabase belum terkonfigurasi. Tambahkan NEXT_PUBLIC_SUPABASE_URL dan NEXT_PUBLIC_SUPABASE_ANON_KEY di Vercel.');setLoading(false);return}setLoading(true);setMsg('');try{if(table){const{data,error}=await supabase.from(table).select('*').order('created_at',{ascending:false}).limit(30);if(error)throw error;setRows(data||[])}else setRows([])}catch(e){setMsg(e.message||String(e))}finally{setLoading(false)}}
 useEffect(()=>{load()},[key]);
 function gps(){navigator.geolocation?.getCurrentPosition(p=>{setLat(String(p.coords.latitude));setLng(String(p.coords.longitude));setAccuracy(String(Math.round(p.coords.accuracy||0)) )},e=>setMsg('GPS: '+e.message),{enableHighAccuracy:true,timeout:20000,maximumAge:0})}
 async function attendance(){if(!supabase)return;if(!lat||!lng)return setMsg('Ambil lokasi GPS terlebih dahulu.');setBusy(true);const{data,error}=await supabase.rpc('record_attendance',{p_qr_token:qr,p_latitude:Number(lat),p_longitude:Number(lng),p_accuracy_m:Number(accuracy||0),p_device_info:navigator.userAgent});setBusy(false);if(error)setMsg(error.message);else{setMsg('Absensi berhasil dicatat.');load()}}
 async function complaint(){if(!supabase||!description)return;setBusy(true);const{data,error}=await supabase.rpc('create_complaint_with_wo',{p_building_id:null,p_equipment_id:null,p_category:'COMPLAINT',p_severity:severity,p_description:description,p_reported_latitude:lat?Number(lat):null,p_reported_longitude:lng?Number(lng):null,p_photo_url:null});setBusy(false);if(error)setMsg(error.message);else{setMsg('Complaint dan Work Order berhasil dibuat.');setDescription('');load()}}
 async function wo(id){setBusy(true);const{error}=await supabase.rpc('update_work_order_status',{p_work_order_id:id,p_status:status,p_note:'Updated from BSS Workforce'});setBusy(false);if(error)setMsg(error.message);else{setMsg('Status Work Order diperbarui.');load()}}
 const row=key==='attendance'?['employee_id','work_date','check_in','check_out','status']:key==='complaint'?['id','severity','description','status','reported_at']:key==='work-orders'?['id','status','priority','title','created_at']:key==='ppm'?['id','scheduled_date','status','equipment_id','assigned_to']:key==='kpi'?['period_month','building_code','employee_id','building_kpi','employee_kpi','grade']:['id','asset_code','name','status','building_id'];
 return <div className="app"><header className="top"><div><div className="brand">BSS ENGINEERING</div><div className="muted">{title}</div></div><Link href="/" style={{color:'#fff'}}>← Dashboard</Link></header><div className="wrap"><nav className="nav">{nav.map(([h,t])=><Link href={h} key={h}>{t}</Link>)}</nav>{!supabaseConfigured&&<div className="err">Supabase environment belum tersedia di deployment ini. Setelah env Vercel tersimpan, lakukan Redeploy.</div>}{msg&&<div className={msg.toLowerCase().includes('berhasil')||msg.includes('terkonfigurasi')?'ok':'err'} style={{marginBottom:12}}>{msg}</div>}
 {key==='attendance'&&<section className="panel form" style={{marginBottom:12}}><h2>Check In / Check Out</h2><input placeholder="QR token" value={qr} onChange={e=>setQr(e.target.value)}/><div className="actions"><button className="btn" onClick={gps}>📍 Ambil GPS</button><span className="small">{lat&&`${lat}, ${lng} • ±${accuracy} m`}</span></div><button className="btn" disabled={busy} onClick={attendance}>{busy?'Memproses…':'Check In / Validasi Absensi'}</button></section>}
 {key==='complaint'&&<section className="panel form" style={{marginBottom:12}}><h2>Buat Complaint</h2><select value={severity} onChange={e=>setSeverity(e.target.value)}><option>MINOR</option><option>MEDIUM</option><option>MAJOR</option><option>CRITICAL</option></select><textarea placeholder="Jelaskan gangguan/equipment/problem" value={description} onChange={e=>setDescription(e.target.value)}/><button className="btn" disabled={busy} onClick={complaint}>{busy?'Menyimpan…':'Simpan Complaint + WO'}</button></section>}
 {key==='work-orders'&&<section className="panel" style={{marginBottom:12}}><h2>Update Status WO</h2><select value={status} onChange={e=>setStatus(e.target.value)}><option>OPEN</option><option>ASSIGNED</option><option>IN_PROGRESS</option><option>DONE</option><option>CANCELLED</option></select><p className="small">Klik tombol pada baris WO untuk menerapkan status.</p></section>}
 <section className="panel"><div className="actions" style={{justifyContent:'space-between'}}><h2 style={{margin:0}}>{title}</h2><button className="btn" onClick={load}>↻ Refresh</button></div>{loading?<p>Memuat database…</p>:!rows.length?<p className="small">Belum ada data.</p>:<div style={{overflow:'auto'}}><table className="table"><thead><tr>{row.map(f=><th key={f}>{f}</th>)}{key==='work-orders'&&<th>Aksi</th>}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{row.map(f=><td key={f}>{String(r[f]??'-')}</td>)}{key==='work-orders'&&<td><button className="btn" onClick={()=>wo(r.id)}>Simpan Status</button></td>}</tr>)}</tbody></table></div>}</section><p className="small" style={{marginTop:12}}>Build 23 • Supabase realtime-ready • {fields.length?`${fields.length} kolom terdeteksi`:''}</p></div></div>}
