'use client';
import {useEffect,useState,useRef} from 'react';
import Link from 'next/link';
import {useParams} from 'next/navigation';
import {supabase} from '../../lib/supabase-browser';
import * as XLSX from 'xlsx';
const labels={attendance:'Absensi',complaint:'Complaint','work-orders':'Work Order',ppm:'PPM Master Plan',kpi:'KPI',operations:'Equipment',reports:'Laporan',management:'Management','ppm-qc':'PPM QC','ppm-schedule':'PPM Schedule','ppm-import':'Import PPM','ppm-execution':'PPM Execution','attendance-monitor':'Monitor Absensi'};
const nav=[['/','Dashboard'],['/attendance','Absensi'],['/complaint','Complaint'],['/work-orders','Work Order'],['/ppm','PPM'],['/operations','Equipment'],['/kpi','KPI'],['/reports','Laporan'],['/qr','QR / Master Data']];
const freqLabel={DAILY:'Harian',WEEKLY:'Mingguan',MONTHLY:'Bulanan','3_MONTHLY':'3 Bulanan','6_MONTHLY':'6 Bulanan',YEARLY:'Tahunan'};
export default function Module(){const{module:key}=useParams();const[rows,setRows]=useState([]),[buildings,setBuildings]=useState([]),[equipment,setEquipment]=useState([]),[msg,setMsg]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[user,setUser]=useState(null);const[form,setForm]=useState({building:'PAL',equipment:'',severity:'MEDIUM',category:'COMPLAINT',title:'',description:'',qr:'',action:'CHECK_IN',status:'OPEN',finding:'',actionTaken:''});const fileRef=useRef(null);const title=labels[key]||key;
async function load(){setLoading(true);try{const{data:{user:u}}=await supabase.auth.getUser();setUser(u);const[b,e]=await Promise.all([supabase.from('buildings').select('code,name').eq('active',true).order('name'),supabase.from('equipment').select('id,asset_code,building_code,area,equipment_type,brand,status,next_ppm_date').order('asset_code')]);setBuildings(b.data||[]);setEquipment(e.data||[]);if(key==='ppm'){const{data,error}=await supabase.from('ppm_master_tasks').select('id,building_code,task_no,category,task,frequency,active').eq('active',true).order('building_code').order('task_no');if(error)throw error;setRows(data||[])}else{const map={attendance:'attendance',complaint:'complaints','work-orders':'work_orders','ppm-schedule':'ppm_schedule',kpi:'kpi_monthly',operations:'equipment','ppm-qc':'ppm_executions','attendance-monitor':'attendance'};if(map[key]){const{data,error}=await supabase.from(map[key]).select('*').order('created_at',{ascending:false}).limit(100);if(error)throw error;setRows(data||[])}else setRows([])}}catch(e){setMsg(e.message||'Gagal membaca database')}finally{setLoading(false)}}
useEffect(()=>{load()},[key]);
const set=(k,v)=>setForm(x=>({...x,[k]:v}));
function gps(){navigator.geolocation?.getCurrentPosition(p=>{setMsg(`GPS siap: ${p.coords.latitude.toFixed(6)}, ${p.coords.longitude.toFixed(6)} ±${Math.round(p.coords.accuracy)}m`);window.__bssgps=p.coords},e=>setMsg('GPS: '+e.message),{enableHighAccuracy:true,timeout:20000,maximumAge:0})}
async function attendance(){if(!user)return setMsg('Silakan Login terlebih dahulu.');if(!form.qr)return setMsg('Masukkan atau scan QR ID lokasi.');const c=window.__bssgps;if(!c)return setMsg('Ambil GPS terlebih dahulu.');setBusy(true);const{data,error}=await supabase.rpc('record_attendance',{p_building_code:form.building,p_qr_id:form.qr,p_lat:c.latitude,p_lng:c.longitude,p_accuracy_m:c.accuracy,p_action:form.action});setBusy(false);setMsg(error?error.message:`${form.action==='CHECK_IN'?'Check In':'Check Out'} berhasil • server ${new Date(data.server_at).toLocaleTimeString('id-ID')}`);if(!error)load()}
async function complaint(){if(!user)return setMsg('Login terlebih dahulu.');if(!form.description)return setMsg('Isi deskripsi gangguan.');setBusy(true);const{data,error}=await supabase.rpc('create_complaint_with_wo',{p_building_code:form.building,p_equipment_id:form.equipment||null,p_category:form.category,p_severity:form.severity,p_title:form.title||'Gangguan Engineering',p_description:form.description});setBusy(false);setMsg(error?error.message:`Complaint ${data?.ticket_no||''} dan WO berhasil dibuat.`);if(!error){set('description','');set('title','');load()}}
async function wo(id){setBusy(true);const{error}=await supabase.rpc('update_work_order_status',{p_work_order_id:id,p_status:form.status});setBusy(false);setMsg(error?error.message:'Status WO berhasil diperbarui.');if(!error)load()}
async function ppmStart(id){setBusy(true);const{data,error}=await supabase.rpc('start_ppm_execution',{p_schedule_id:id});setBusy(false);setMsg(error?error.message:`PPM dimulai: ${data?.execution_id||''}`);if(!error)load()}
async function qc(id,ok){setBusy(true);const{error}=await supabase.rpc('approve_ppm_execution',{p_execution_id:id,p_qc_status:ok?'APPROVED':'REJECTED',p_note:ok?'QC OK':'QC perlu perbaikan'});setBusy(false);setMsg(error?error.message:'Hasil QC tersimpan.');if(!error)load()}
async function addEquipment(){if(!form.asset)return setMsg('Asset code wajib.');const{error}=await supabase.from('equipment').insert({asset_code:form.asset,building_code:form.building,area:form.area||'General',equipment_type:form.type||'OTHER',brand:form.brand||null,status:'ACTIVE'});setMsg(error?error.message:'Equipment berhasil ditambahkan.');if(!error){set('asset','');load()}}
async function importFile(e){const f=e.target.files?.[0];if(!f)return;setBusy(true);try{const wb=XLSX.read(await f.arrayBuffer(),{type:'array'}),json=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});const rows=json.map((r,i)=>({row:i+2,tanggal_ppm:r.Tanggal||r.tanggal_ppm||r.Tgl,gedung:r.Gedung||r.gedung||r.Site,equipment_id:r.Equipment||r.equipment_id||r['Kode Asset'],equipment_name:r['Equipment Name']||r.equipment_name||'',lokasi:r.Lokasi||r.lokasi||'',jenis_ppm:r['Jenis PPM']||r.jenis_ppm||'PREVENTIVE',frekuensi:r.Frekuensi||r.frekuensi||'MONTHLY',teknisi:r.Teknisi||r.teknisi||'',shift:r.Shift||r.shift||'',status:r.Status||r.status||'PLANNED',target:String(r.Target||1),keterangan:r.Keterangan||r.keterangan||''}));const{data,error}=await supabase.rpc('import_ppm_batch',{p_period_month:new Date().toISOString().slice(0,10),p_file_name:f.name,p_rows:rows});if(error)throw error;const batch=data?.batch_id;if(batch){const c=await supabase.rpc('commit_ppm_import',{p_batch_id:batch});if(c.error)throw c.error;setMsg(`Import selesai: ${c.data?.inserted||0} jadwal masuk.`)}else setMsg('Import diproses.')}catch(err){setMsg(err.message||'Import gagal')}finally{setBusy(false);if(fileRef.current)fileRef.current.value=''}}
const cols=key==='ppm'?['building_code','task_no','category','task','frequency','active']:key==='attendance'?['building_code','work_date','check_in_at','check_out_at','validation_status']:key==='complaint'?['ticket_no','building_code','severity','status','description','reported_at']:key==='work-orders'?['wo_no','building_code','priority','status','description']:key==='ppm-schedule'?['scheduled_date','equipment_id','assigned_to','status','frequency']:key==='kpi'?['period_month','building_code','employee_id','building_kpi','employee_kpi','grade']:key==='operations'?['asset_code','building_code','area','equipment_type','brand','status','next_ppm_date']:key==='ppm-qc'?['ppm_schedule_id','employee_id','status','qc_status','completed_at']:['id','status','created_at'];
return <div className="modulePage"><header className="moduleHead"><div><b>BSS ENGINEERING</b><h1>{title}</h1></div><div><span className="statusDot">● Database Connected</span> <Link href="/">← Dashboard</Link></div></header><div className="moduleBody"><nav className="moduleNav">{nav.map(([h,t])=><Link href={h} key={h}>{t}</Link>)}</nav>{msg&&<div className={'notice '+(msg.toLowerCase().includes('berhasil')||msg.toLowerCase().includes('selesai')||msg.toLowerCase().includes('import')?'success':'error')}>{msg}</div>}
{key==='ppm'&&<section className="panel form"><div className="formGrid"><label>Filter Gedung<select value={form.building} onChange={e=>set('building',e.target.value)}><option value="ALL">Semua Gedung</option>{buildings.map(b=><option value={b.code} key={b.code}>{b.name}</option>)}</select></label><label>Filter Frekuensi<select onChange={e=>set('frequencyFilter',e.target.value)}><option value="ALL">Semua Frekuensi</option>{Object.entries(freqLabel).map(([v,n])=><option value={v} key={v}>{n}</option>)}</select></label></div><p className="muted">Master PPM hasil input dari file PPM 52 4 GEDUNG. Data ini menjadi dasar penyusunan jadwal dan eksekusi PPM.</p></section>}
{key==='attendance'&&<section className="panel form"><div className="formGrid"><label>Gedung<select value={form.building} onChange={e=>set('building',e.target.value)}>{buildings.map(b=><option value={b.code} key={b.code}>{b.name}</option>)}</select></label><label>QR ID / hasil scan<input value={form.qr} onChange={e=>set('qr',e.target.value)} placeholder="UUID QR lokasi"/></label></div><div className="actions"><button className="btn secondary" onClick={gps}>📍 Ambil GPS</button><button className="btn" onClick={()=>set('action',form.action==='CHECK_IN'?'CHECK_OUT':'CHECK_IN')}>{form.action==='CHECK_IN'?'Mode Check In':'Mode Check Out'}</button><button className="btn primary" disabled={busy} onClick={attendance}>{busy?'Memproses…':form.action==='CHECK_IN'?'CHECK IN':'CHECK OUT'}</button></div><p className="muted">Validasi: akun + QR + GPS + akurasi + geofence + waktu server.</p></section>}
{key==='complaint'&&<section className="panel form"><div className="formGrid"><label>Gedung<select value={form.building} onChange={e=>set('building',e.target.value)}>{buildings.map(b=><option value={b.code} key={b.code}>{b.name}</option>)}</select></label><label>Equipment<select value={form.equipment} onChange={e=>set('equipment',e.target.value)}><option value="">Tidak terkait / umum</option>{equipment.filter(x=>x.building_code===form.building).map(x=><option value={x.id} key={x.id}>{x.asset_code} • {x.equipment_type}</option>)}</select></label><label>Severity<select value={form.severity} onChange={e=>set('severity',e.target.value)}><option>MINOR</option><option>MEDIUM</option><option>MAJOR</option><option>CRITICAL</option></select></label><label>Category<select value={form.category} onChange={e=>set('category',e.target.value)}><option>COMPLAINT</option><option>BREAKDOWN</option><option>PPM_FINDING</option></select></label></div><input value={form.title} onChange={e=>set('title',e.target.value)} placeholder="Judul gangguan"/><textarea value={form.description} onChange={e=>set('description',e.target.value)} placeholder="Deskripsi lengkap gangguan..."/><button className="btn primary" disabled={busy} onClick={complaint}>Simpan Complaint + Buat WO</button></section>}
{key==='work-orders'&&<section className="panel form"><label>Status baru<select value={form.status} onChange={e=>set('status',e.target.value)}><option>OPEN</option><option>ASSIGNED</option><option>IN_PROGRESS</option><option>DONE</option><option>CANCELLED</option></select></label><p className="muted">Pilih status lalu klik Aksi pada WO.</p></section>}
{key==='operations'&&<section className="panel form"><h2>Tambah Equipment</h2><div className="formGrid"><input value={form.asset||''} onChange={e=>set('asset',e.target.value)} placeholder="Asset Code"/><select value={form.building} onChange={e=>set('building',e.target.value)}>{buildings.map(b=><option value={b.code} key={b.code}>{b.name}</option>)}</select><input value={form.area||''} onChange={e=>set('area',e.target.value)} placeholder="Area"/><input value={form.type||''} onChange={e=>set('type',e.target.value)} placeholder="AC / PANEL / PUMP / GENSET"/><input value={form.brand||''} onChange={e=>set('brand',e.target.value)} placeholder="Brand"/></div><button className="btn primary" onClick={addEquipment}>+ Simpan Equipment</button></section>}
{key==='ppm-import'&&<section className="panel form"><h2>Import Excel PPM</h2><p className="muted">Header: Tanggal, Gedung, Equipment, Equipment Name, Lokasi, Jenis PPM, Frekuensi, Teknisi, Shift, Status, Target, Keterangan.</p><input ref={fileRef} type="file" accept=".xlsx,.xls,.csv" onChange={importFile}/></section>}
{key==='ppm-qc'&&<section className="panel"><h2>Supervisor QC</h2><p className="muted">Approve/reject PPM yang sudah selesai.</p></section>}
<section className="panel tablePanel"><div className="panelTitle"><div><h2>{title}</h2><small>{rows.length} record • live database</small></div><button className="btn secondary" onClick={load}>↻ Refresh</button></div>{loading?<div className="loading">Memuat database…</div>:rows.length===0?<div className="empty">Belum ada data transaksi.</div>:<div className="tableWrap"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}{['work-orders','ppm','ppm-qc'].includes(key)&&<th>Aksi</th>}</tr></thead><tbody>{rows.filter(r=>key!=='ppm'||(form.building==='ALL'||r.building_code===form.building)&&( !form.frequencyFilter||form.frequencyFilter==='ALL'||r.frequency===form.frequencyFilter)).map((r,i)=><tr key={r.id||i}>{cols.map(c=><td key={c}>{c==='frequency'?freqLabel[r[c]]||r[c]:String(r[c]??'—')}</td>)}{key==='work-orders'&&<td><button className="mini" disabled={busy} onClick={()=>wo(r.id)}>Simpan {form.status}</button></td>}{key==='ppm'&&<td><button className="mini" disabled>{r.active?'Master':'Nonaktif'}</button></td>}{key==='ppm-qc'&&<td><button className="mini" onClick={()=>qc(r.id,true)}>Approve</button><button className="mini danger" onClick={()=>qc(r.id,false)}>Reject</button></td>}</tr>)}</tbody></table></div>}</section>
{key==='reports'&&<section className="panel"><h2>Export Laporan</h2><p className="muted">Data di atas dapat diekspor dari browser; gunakan Print → Save PDF untuk PDF resmi.</p><button className="btn" onClick={()=>window.print()}>🖨 Print / PDF</button></section>}
</div></div>}
