'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {supabase} from '../../lib/supabase-browser';
export default function Attendance(){
 const [user,setUser]=useState(null),[sites,setSites]=useState([]),[qrs,setQrs]=useState([]),[building,setBuilding]=useState(''),[qr,setQr]=useState(''),[status,setStatus]=useState('Siap'),[detail,setDetail]=useState(''),[loading,setLoading]=useState(false),[history,setHistory]=useState([]);
 async function load(){const {data:{user:u}}=await supabase.auth.getUser();setUser(u||null);const {data:s}=await supabase.from('buildings').select('code,name,geofence_radius_m,latitude,longitude').eq('active',true).order('name');setSites(s||[]);if(s?.length&&!building)setBuilding(s[0].code);const {data:q}=await supabase.from('qr_locations').select('id,building_code,label').eq('active',true).order('building_code');setQrs(q||[]);const {data:h}=await supabase.from('attendance_test_events').select('action,building_code,created_at,accuracy_m').order('created_at',{ascending:false}).limit(8);setHistory(h||[])}
 useEffect(()=>{load()},[]);const selectedQR=qrs.find(x=>x.id===qr);const selectedSite=sites.find(x=>x.code===building);
 const gps=()=>new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:20000,maximumAge:0}));
 async function test(action){setLoading(true);setStatus('Mengambil GPS…');setDetail('');try{if(!user){setStatus('Belum login');setDetail('Login dulu agar sistem dapat mengaitkan absensi dengan akun karyawan.');return}const p=await gps();const {data,error}=await supabase.rpc('record_attendance_test',{p_building_code:building,p_lat:p.coords.latitude,p_lng:p.coords.longitude,p_accuracy_m:p.coords.accuracy,p_action:action});if(error)throw error;setStatus('ABSENSI UJI BERHASIL');setDetail(`Tersimpan di Supabase • ${data.server_at} • akurasi ${Math.round(p.coords.accuracy)} m`);await load()}catch(e){setStatus('Gagal');setDetail(e.message||'Gagal membaca GPS')}finally{setLoading(false)}}
 async function production(action){setLoading(true);setStatus('Validasi QR + GPS…');setDetail('');try{if(!user){setStatus('Belum login');setDetail('Login terlebih dahulu.');return}if(!qr){setStatus('QR belum dipilih');setDetail('Pilih QR lokasi.');return}const p=await gps();const {data,error}=await supabase.rpc('record_attendance',{p_building_code:building,p_qr_id:qr,p_lat:p.coords.latitude,p_lng:p.coords.longitude,p_accuracy_m:p.coords.accuracy,p_action:action});if(error)throw error;setStatus(data?.ok?'ABSENSI PRODUKSI BERHASIL':'ABSENSI DITOLAK');setDetail(data?.reason||JSON.stringify(data));await load()}catch(e){setStatus('Belum lolos validasi');setDetail(e.message||'Gagal')}finally{setLoading(false)}}
 return <main className="attendancePage"><div className="attendanceCard"><Link href="/">← Dashboard</Link><img src="/bss-engineering-logo.png" className="attLogo"/><h1>Absensi BSS Engineering</h1><p className="muted">QR + GPS + server time + Supabase.</p>{!user&&<div className="notice">Anda belum login. <Link href="/login">Login sekarang →</Link></div>}<label>Gedung<select value={building} onChange={e=>{setBuilding(e.target.value);setQr('')}}>{sites.map(s=><option key={s.code} value={s.code}>{s.name}</option>)}</select></label><label>QR Lokasi<select value={qr} onChange={e=>setQr(e.target.value)}><option value="">Pilih QR…</option>{qrs.filter(q=>q.building_code===building).map(q=><option key={q.id} value={q.id}>{q.label} • {q.id.slice(0,8)}</option>)}</select></label><div className="qrBox">{selectedQR?<><b>{selectedQR.label}</b><code>{selectedQR.id}</code><Link href="/qr">Buka halaman QR →</Link></>:<span>QR belum dipilih</span>}</div><div className="actionGrid"><button disabled={loading} onClick={()=>test('CHECK_IN')}>CHECK IN UJI<br/><small>tulis ke DB</small></button><button disabled={loading} onClick={()=>test('CHECK_OUT')}>CHECK OUT UJI<br/><small>tulis ke DB</small></button></div><div className="prodBox"><b>Absensi Produksi</b><span>QR: {selectedQR?'OK':'belum'} • GPS: aktif • Geofence: {selectedSite?.latitude?'siap':'BELUM DISET'}</span><div className="actionGrid"><button disabled={loading||!qr} onClick={()=>production('CHECK_IN')}>CHECK IN</button><button disabled={loading||!qr} onClick={()=>production('CHECK_OUT')}>CHECK OUT</button></div></div><div className="result"><b>{status}</b><p>{detail}</p></div><h3>Riwayat Uji</h3>{history.map((h,i)=><div className="history" key={i}><span>{h.action}</span><b>{h.building_code}</b><small>{new Date(h.created_at).toLocaleString('id-ID')}</small></div>)}</div></main>}
