'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {supabase} from '../../lib/supabase-browser';
const SITES=[['PAL','Palmerah'],['PEC','Pecenongan'],['SAN','Sangaji'],['PH','Permata Hijau']];
export default function Attendance(){const[building,setBuilding]=useState('PAL'),[qr,setQr]=useState(null),[sites,setSites]=useState(SITES),[pos,setPos]=useState(null),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[logged,setLogged]=useState(false),[user,setUser]=useState(null);useEffect(()=>{(async()=>{const{data:{user:u}}=await supabase.auth.getUser();setUser(u);const{data}=await supabase.from('buildings').select('code,name,latitude,longitude,geofence_radius_m').eq('active',true).in('code',['PAL','PEC','SAN','PH']).order('display_order');if(data?.length)setSites(data.map(x=>[x.code,x.name]));const{data:q}=await supabase.from('qr_locations').select('id,building_code,label').eq('active',true);setQr(q||[])})()},[]);
function locate(){setStatus('Mengambil lokasi GPS…');navigator.geolocation.getCurrentPosition(p=>{setPos({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy});setStatus(`GPS siap • akurasi ±${Math.round(p.coords.accuracy)} m`)},e=>setStatus('GPS gagal: '+e.message),{enableHighAccuracy:true,timeout:20000,maximumAge:0})}
async function check(action){if(!user)return setStatus('Silakan login terlebih dahulu.');if(!pos)return setStatus('Tekan Ambil Lokasi GPS terlebih dahulu.');const q=qr.find(x=>x.building_code===building);if(!q)return setStatus('QR gedung belum tersedia. Buka Master QR dan buat QR untuk gedung ini.');setBusy(true);setStatus(action==='CHECK_IN'?'Memproses Check In…':'Memproses Check Out…');const{data,error}=await supabase.rpc('record_attendance',{p_building_code:building,p_qr_id:q.id,p_lat:pos.lat,p_lng:pos.lng,p_accuracy_m:pos.accuracy,p_action:action});setBusy(false);if(error){setStatus('Gagal: '+error.message);return}setLogged(action==='CHECK_IN');setStatus(action==='CHECK_IN'?'✅ CHECK IN berhasil tersimpan di database.':'✅ CHECK OUT berhasil tersimpan di database.');}
return <main className="modulePage"><header className="moduleHead"><div><b>BSS ENGINEERING</b><h1>Absensi</h1></div><Link href="/">← Dashboard</Link></header><div className="moduleBody"><div className="moduleNav"><Link href="/attendance">Absensi</Link><Link href="/attendance-monitor">Monitor</Link><Link href="/qr">Master QR & Lokasi</Link></div><section className="panel"><h2>Check In / Check Out</h2><p className="muted">Sistem memvalidasi akun, gedung, QR, GPS, radius dan waktu server.</p><div className="formGrid"><label>Nama Akun<input value={user?.email||'Belum login'} readOnly/></label><label>Pilih Gedung<select value={building} onChange={e=>setBuilding(e.target.value)}>{sites.map(([c,n])=><option key={c} value={c}>{n}</option>)}</select></label></div><div className="actions"><button className="btn secondary" onClick={locate}>📍 Ambil Lokasi GPS</button><button className="btn primary" disabled={busy||!user||!pos||logged} onClick={()=>check('CHECK_IN')}>✓ CHECK IN</button><button className="btn danger" disabled={busy||!user||!pos||!logged} onClick={()=>check('CHECK_OUT')}>↪ CHECK OUT</button></div>{pos&&<div className="notice success">GPS: {pos.lat.toFixed(6)}, {pos.lng.toFixed(6)} • akurasi ±{Math.round(pos.accuracy)} m</div>}{status&&<div className={status.startsWith('Gagal')?'notice error':'notice success'}>{status}</div>}</section><section className="panel"><h3>QR yang tersedia</h3><div className="siteGrid">{sites.map(([c,n])=><div className="siteCard" key={c}><b>{n}</b><span>{qr.find(x=>x.building_code===c)?.label||'QR belum dibuat'}</span><small>{qr.find(x=>x.building_code===c)?'● Aktif':'○ Belum tersedia'}</small></div>)}</div></section></div></main>}
