'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {supabase} from '../../lib/supabase-browser';
const FALLBACK=[{code:'PAL',name:'Palmerah'},{code:'PEC',name:'Pecenongan'},{code:'SAN',name:'Sangaji'},{code:'PH',name:'Permata Hijau'}];

export default function Attendance(){
 const[sites,setSites]=useState(FALLBACK),[qr,setQr]=useState([]),[building,setBuilding]=useState('PAL'),[scannedQr,setScannedQr]=useState(null),[pos,setPos]=useState(null),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[logged,setLogged]=useState(false),[user,setUser]=useState(null),[camera,setCamera]=useState(false);
 const video=useRef(null),stream=useRef(null);
 useEffect(()=>{(async()=>{const{data:{user:u}}=await supabase.auth.getUser();setUser(u);const{data}=await supabase.from('buildings').select('code,name,latitude,longitude,geofence_radius_m').eq('active',true).in('code',['PAL','PEC','SAN','PH']).order('display_order');if(data?.length){setSites(data);setBuilding(data[0].code)}const{data:q}=await supabase.from('qr_locations').select('id,building_code,label,active').eq('active',true);setQr(q||[])})();return()=>stream.current?.getTracks().forEach(t=>t.stop())},[]);
 const site=sites.find(s=>s.code===building);
 const gpsRequired=Boolean(site?.latitude&&site?.longitude);
 function locate(){setStatus('Mengambil lokasi GPS…');if(!navigator.geolocation)return setStatus('Browser tidak mendukung GPS.');navigator.geolocation.getCurrentPosition(p=>{setPos({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy});setStatus(`GPS siap • akurasi ±${Math.round(p.coords.accuracy)} m`)},e=>setStatus('GPS gagal: '+e.message),{enableHighAccuracy:true,timeout:20000,maximumAge:0})}
 async function scan(){if(!('BarcodeDetector'in window))return setStatus('Scanner QR tidak tersedia di browser ini. Gunakan Chrome/Edge terbaru atau pilih QR dari daftar.');try{setCamera(true);stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});video.current.srcObject=stream.current;await video.current.play();const detector=new BarcodeDetector({formats:['qr_code']});const loop=async()=>{if(!video.current||!stream.current)return;try{const found=await detector.detect(video.current);const value=found[0]?.rawValue;if(value){const q=qr.find(x=>x.id===value);if(q){setScannedQr(q);setBuilding(q.building_code);setStatus(`QR valid: ${q.label||q.id}`)}else setStatus('QR terbaca tetapi tidak terdaftar di Master QR.');stop()}}catch{}requestAnimationFrame(loop)};loop()}catch(e){setCamera(false);setStatus('Kamera gagal: '+e.message)}}
 function stop(){setCamera(false);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null}
 function chooseQr(id){const q=qr.find(x=>x.id===id);if(q){setScannedQr(q);setBuilding(q.building_code);setStatus(`QR dipilih: ${q.label||q.id}`)}}
 async function check(action){if(!user)return setStatus('Silakan login terlebih dahulu.');if(!scannedQr)return setStatus('Scan QR lokasi terlebih dahulu.');if(gpsRequired&&!pos)return setStatus('Gedung ini sudah memiliki geofence. Ambil lokasi GPS terlebih dahulu.');setBusy(true);setStatus(action==='CHECK_IN'?'Memproses Check In…':'Memproses Check Out…');const{error}=await supabase.rpc('record_attendance',{p_building_code:building,p_qr_id:scannedQr.id,p_lat:pos?.lat??null,p_lng:pos?.lng??null,p_accuracy_m:pos?.accuracy??null,p_action:action});setBusy(false);if(error){setStatus('Gagal: '+error.message);return}setLogged(action==='CHECK_IN');setStatus(action==='CHECK_IN'?'✅ CHECK IN berhasil tersimpan di database.':'✅ CHECK OUT berhasil tersimpan di database.');}
 return <main className="modulePage"><header className="moduleHead"><div><b>BSS ENGINEERING</b><h1>Absensi</h1></div><Link href="/">← Dashboard</Link></header><div className="moduleBody"><div className="moduleNav"><Link href="/attendance">Absensi</Link><Link href="/attendance-monitor">Monitor</Link><Link href="/qr">Master QR & Lokasi</Link></div>
 <section className="panel"><h2>Check In / Check Out</h2><p className="muted">Scan QR lokasi. Jika koordinat gedung sudah dikonfigurasi, sistem juga memvalidasi GPS + radius. Jika belum, QR digunakan sebagai validasi lokasi.</p><div className="formGrid"><label>Nama Akun<input value={user?.email||'Belum login'} readOnly/></label><label>Gedung<select value={building} onChange={e=>{setBuilding(e.target.value);setScannedQr(null)}}>{sites.map(s=><option key={s.code} value={s.code}>{s.name}</option>)}</select></label></div><div className="actions"><button className="btn primary" onClick={scan} disabled={busy}>📷 Scan QR Lokasi</button><button className="btn secondary" onClick={locate} disabled={busy||!gpsRequired}>📍 Ambil GPS</button><button className="btn primary" disabled={busy||!user||!scannedQr||logged||(gpsRequired&&!pos)} onClick={()=>check('CHECK_IN')}>✓ CHECK IN</button><button className="btn danger" disabled={busy||!user||!scannedQr||!logged||(gpsRequired&&!pos)} onClick={()=>check('CHECK_OUT')}>↪ CHECK OUT</button></div>{camera&&<div className="scanner"><video ref={video} playsInline muted/><button className="btn danger" onClick={stop}>Tutup Scanner</button></div>}{scannedQr&&<div className="notice success">QR aktif: <b>{scannedQr.label||scannedQr.id}</b> • {building}{gpsRequired?' • GPS + geofence aktif':' • mode QR-only'}</div>}{pos&&<div className="notice success">GPS: {pos.lat.toFixed(6)}, {pos.lng.toFixed(6)} • akurasi ±{Math.round(pos.accuracy)} m</div>}{status&&<div className={status.startsWith('Gagal')?'notice error':'notice success'}>{status}</div>}</section>
 <section className="panel"><h3>QR aktif</h3><div className="siteGrid">{sites.map(s=>{const list=qr.filter(q=>q.building_code===s.code);return <div className="siteCard" key={s.code}><b>{s.name}</b><span>{s.latitude&&s.longitude?'GPS + geofence':'QR-only sampai GPS dikonfigurasi'}</span><small>{list.length?list.map(q=><button key={q.id} className="mini" onClick={()=>chooseQr(q.id)}>{q.label||'Pilih QR'}</button>):'QR belum tersedia'}</small></div>})}</div></section>
 </div></main>
}
