revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.can_manage_engineering() from public, anon, authenticated;
revoke all on function public.is_super_admin() from public, anon, authenticated;
revoke all on function public.validate_attendance(uuid,text,uuid,double precision,double precision,double precision) from public, anon, authenticated;
revoke all on function public.refresh_kpi_month(date) from public, anon, authenticated;
revoke all on function public.process_kpi_refresh_queue(integer) from public, anon, authenticated;
revoke all on function public.request_kpi_refresh(uuid) from public, anon, authenticated;
revoke all on function public.record_attendance(text,uuid,double precision,double precision,double precision,text) from public, anon;
revoke all on function public.record_attendance_test(text,double precision,double precision,double precision,text) from public, anon;
revoke all on function public.create_complaint_with_wo(text,uuid,text,text,text,text) from public, anon;
revoke all on function public.update_work_order_status(uuid,text) from public, anon;
revoke all on function public.start_ppm_execution(uuid) from public, anon;
revoke all on function public.complete_ppm_execution(uuid) from public, anon;
revoke all on function public.approve_ppm_execution(uuid,text,text) from public, anon;
revoke all on function public.import_ppm_batch(date,text,jsonb) from public, anon;
revoke all on function public.commit_ppm_import(uuid) from public, anon;
grant execute on function public.record_attendance(text,uuid,double precision,double precision,double precision,text) to authenticated;
grant execute on function public.create_complaint_with_wo(text,uuid,text,text,text,text) to authenticated;
grant execute on function public.update_work_order_status(uuid,text) to authenticated;
grant execute on function public.start_ppm_execution(uuid) to authenticated;
grant execute on function public.complete_ppm_execution(uuid) to authenticated;
grant execute on function public.approve_ppm_execution(uuid,text,text) to authenticated;
grant execute on function public.import_ppm_batch(date,text,jsonb) to authenticated;
grant execute on function public.commit_ppm_import(uuid) to authenticated;
